'use strict';

// Builds the phone wallet into site/wallet/ -- deployed on the same
// Cloudflare Pages origin as the rest of the site (which already has HTTPS,
// the precondition for a service worker and install). esbuild bundles the
// CJS app + the shared common-credo-core engine into one self-contained
// browser script (same nodePaths trick as build-site.js / the Phase 1 spike,
// so nostr-tools and @noble/hashes resolve from core/node_modules). The PWA
// shell (manifest, service worker, icons) is added in Phase 4.

const fs = require('fs');
const path = require('path');
const esbuild = require('esbuild');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(__dirname, 'src');
const OUT = path.join(ROOT, 'site', 'wallet');

async function main() {
  fs.mkdirSync(OUT, { recursive: true });

  await esbuild.build({
    entryPoints: [path.join(SRC, 'app.js')],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2020',
    outfile: path.join(OUT, 'app.js'),
    legalComments: 'none',
    nodePaths: [path.join(ROOT, 'core', 'node_modules')],
  });
  console.log('wrote site/wallet/app.js');

  for (const f of ['index.html', 'style.css', 'manifest.webmanifest', 'sw.js']) {
    fs.copyFileSync(path.join(SRC, f), path.join(OUT, f));
    console.log(`wrote site/wallet/${f}`);
  }

  // Icons (generated by generate-icons.js).
  const iconsSrc = path.join(SRC, 'icons');
  const iconsOut = path.join(OUT, 'icons');
  fs.mkdirSync(iconsOut, { recursive: true });
  for (const f of fs.readdirSync(iconsSrc)) {
    fs.copyFileSync(path.join(iconsSrc, f), path.join(iconsOut, f));
    console.log(`wrote site/wallet/icons/${f}`);
  }

  console.log('wallet build complete.');
}

main().catch((e) => { console.error(e); process.exit(1); });
